version: '3'

services:
  phpapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: phpapp:123
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    container_name: myphp-app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: "mysql"
      MYSQL_ROOT_PASSWORD: "my!!!root!!!pw" 
    container_name: myphp-db