version: '3'

services:
  db:
    image: mysql
    restart: always
    container_name: myphpapp-db
    environment: 
      MYSQL_USER: mysql
      MYSQL_PASSWORD: somepass
      MYSQL_DATABASE: somedatabase
    volumes:
      - "myvol:/var/lib/mysql"

volumes:
  myvol:
    name: myvol   
  